############# profile default #######################
my:
    servers:
        - serverDefault1
        - serverDefault2
        - serverDefault3

application:
  name: lab-spring-boot 
  version: 1.0
  environment: default  

---

############# profile local #######################
spring:
    profiles: local

environment: local

my:
    servers:
        - serverLocal1
        - serverLocal2
        - serverLocal3

---

############# profile devel #######################
spring:
    profiles: devel

application:
    environment: devel

my:
    servers:
        - serverDevel1
        - serverDevel2
        - serverDevel3
        
---

############# profile pred #######################	
spring:
    profiles: pred

application:
    environment: pred

my:
    servers:
        - serverPred1
        - serverPred2
        - serverPred3

---

############# profile prod #######################	
spring:
    profiles: prod

application:
    environment: prod

my:
    servers:
        - serverProd1
        - serverProd2
        - serverProd3    		